version: 2.1
jobs:
  say-hello:
    docker:
      - image: node:13-alpine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk update
            apk add --no-cache python3
            pip3 install --upgrade pip
            pip3 install awscli
            apk add --no-cache bash
            apk add --no-cache curl
      - run:
          name: step 1
          command: |
            npm install
            echo "SUCCESS"
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
