version: 2.1
jobs:
  say-hello:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y curl
 
      - run:
          name: Install nodjs
          command: |
             curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - &&\

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
