version: 2.1
jobs:
  say-hello:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install dependencies
          command: echo "hello" 

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
