version: 2.1
jobs:
  say-hello:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y curl
            curl -s https://deb.nodesource.com/setup_13.x | sudo bash
            sudo apt install -y nodejs

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
