version: 2.1
jobs:
  say-hello:
    docker:
      - image: python:3.9.16-alpine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache bash
            apk add --no-cache curl
            apk add --update npm
      - run:
          name: step 1
          command: |
            npm install
            echo "SUCCESS"
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
