version: 2.1
jobs:
  say-hello:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y curl
 
      - run:
          name: Install nodjs
          command: |
             npm install -g n
             n 13.8.0

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
