version: 2.1
jobs:
  say-hello:
    docker:
      - image: python:3.9.16-alpine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache bash
            apk add --no-cache curl
      - run:
          name: step 1
          command: |
            if curl "http://54.164.88.108:3030/api/status" | grep "ok"
            then
              return 0
            else
              return 1
            fi
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
