version: 2.1
jobs:
  say-hello:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            echo | pwd


workflows:
  say-hello-workflow:
    jobs:
      - say-hello
