version: 2.1
jobs:
  say-hello:
    docker:
      - image: python:3.9.16-alpine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache bash
            echo | pwd
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
